spring:
  kafka:
    bootstrap-servers: localhost:29092
  data:
    mongodb:
      uri: mongodb://localhost:27017/codeexecutor

server:
  port: 8082

app:
  submission-api:
    base-url: http://localhost:8080
