spring:
  kafka:
    bootstrap-servers: kafka:9092
  data:
    mongodb:
      uri: mongodb://mongo:27017/codeexecutor

server:
  port: 8082

app:
  submission-api:
    base-url: http://submission-api:8080
