spring:
  application:
    name: user-service
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/codeexecutor}


server:
  port: 8088

app:
  issuer: ${ISSUER:http://localhost:8088}
  front-origin: ${FRONT_ORIGIN:http://localhost:5173}
  security:
    client-secret: ${OAUTH_CLIENT_SECRET:dev-secret}

security:
  jwt:
    issuer: ${app.issuer}
    accessMinutes: 30
    privatePemPath: "${JWT_PRIVATE_PATH:}"
    publicPemPath:  "${JWT_PUBLIC_PATH:}"

logging:
  level:
    root: ${LOG_LEVEL:INFO}

