spring:
  application:
    name: submission-api
  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:29092}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/codeevaluator}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${SPRING_SECURITY_OAUTH2_RESOURCESERVER_JWT_JWK_SET_URI:http://localhost:8088/.well-known/jwks.json}

server:
  port: ${SERVER_PORT:8080}

app:
  kafka:
    topics:
      submissions: ${APP_TOPICS_SUBMISSIONS:submissions}
  api:
    key: ${INTERNAL_API_KEY}
