spring:
  application:
    name: submission-api

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
    properties:
      allow.auto.create.topics: true
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: submissions-view-group
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring.json.trusted.packages: 'com.calata.evaluator.contracts.*'
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/codeexecutor}
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${JWK_SET_URI:http://localhost:8088/.well-known/jwks.json}

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: ${LOG_LEVEL:INFO}

app:
  kafka:
    groups:
      submissions: submissions-group
      submissions-view: submissions-view-group

internal:
  api:
    key: ${INTERNAL_API_KEY}
front:
  origin: ${FRONT_ORIGIN:http://localhost:5173}
services:
  submissions:
    base-url: ${SUBMISSIONS_API_URL:http://submission-api:8080}
  authorship:
    base-url: ${AUTHORSHIP_API_URL:http://authorship-service:8092}
